<a href="https://colab.research.google.com/github/cayan701/pytorch-intro/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## introduction to Tensors

### Creating tensors

> PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html



In [1]:
import torch
print(torch.__version__)

2.5.1+cu124


In [2]:
# scalar
scalar = torch.tensor(4)
scalar

tensor(4)

In [3]:
scalar.ndim

0

In [5]:
 # Vector
vector = torch.tensor([10, 10])
vector

tensor([10, 10])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[5, 2], [6, 9]])
MATRIX

tensor([[5, 2],
        [6, 9]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([5, 2])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [5, 6, 2], [7, 2, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [5, 6, 2],
         [7, 2, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 2],
        [7, 2, 5]])

### Random Tensors

Why random tensors ?

Random tensors are important becsuse the way many neural network learn is that they start with tensors full of random numbers and then adjust those number to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at the data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/main/generated/torch.rand.html


In [ ]:
# Create a random tensors of size (3, 4)
random_tensors = torch.ran(3, 4)